function T_xyz = Txyz(pose)
%TXYZ
%    T_XYZ = TXYZ(X,Y,Z,A,B,R)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    28-May-2021 11:55:57
x = pose(1);
y = pose(2);
z = pose(3);
a = pose(4);
b = pose(5);
r = pose(6);

t2 = cos(a);
t3 = cos(b);
t4 = sin(a);
t5 = sin(b);
t6 = cos(r);
t7 = sin(r);
T_xyz = reshape([t3.*t6,t2.*t7+t4.*t5.*t6,t4.*t7-t2.*t5.*t6,0.0,-t3.*t7,t2.*t6-t4.*t5.*t7,t4.*t6+t2.*t5.*t7,0.0,t5,-t3.*t4,t2.*t3,0.0,conj(x),conj(y),conj(z),1.0],[4,4]);
