function T_zyx = Tzyx(pose)
%TZYX_MF
%    T_ZYX = TZYX_MF(X,Y,Z,A,B,R)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    23-Mar-2021 10:08:04
x = pose(1);
y = pose(2);
z = pose(3);
a = pose(4);
b = pose(5);
r = pose(6);

t2 = cos(a);
t3 = cos(b);
t4 = sin(a);
t5 = sin(b);
t6 = cos(r);
t7 = sin(r);
T_zyx = reshape([t2.*t3,t3.*t4,-t5,0.0,-t4.*t6+t2.*t5.*t7,t2.*t6+t4.*t5.*t7,t3.*t7,0.0,t4.*t7+t2.*t5.*t6,-t2.*t7+t4.*t5.*t6,t3.*t6,0.0,conj(x),conj(y),conj(z),1.0],[4,4]);
